"""New document/identity bookkeeping for this incomplete gate; never reference behavior execution."""
import importlib.util, pathlib, json, hashlib, functools, re, csv, io
OUT=pathlib.Path(__file__).parent
sp=importlib.util.spec_from_file_location('bookkeeping',OUT/'bookkeeping.py'); b=importlib.util.module_from_spec(sp);sp.loader.exec_module(b)
b.blob=functools.lru_cache(None)(b.blob)
A=b.ACT; P=b.PRE; C=b.C3; R='8c5911e4a4b07b07e832e4bb0d5d8859e88b4a9b'; G=b.BASE+'B14/integration-stage-1/'
g=b.obj(A,G+'actual-request-B02.json'); reg=b.obj(A,G+'finding-registration.json'); original=b.obj(b.ORIG,'review/global-independent-review/2026-10-03-fd82a639/findings.json'); originals={x['id']:x for x in original}; plan=b.obj(b.PLAN,'review/remediation-20261003-prepare/finding-acceptance.json'); owner=b.obj(P,b.BASE+'B02/integration-stage-1/finding-registration.json')
def save(n,v):b.save(n,v)
def sha(x):return hashlib.sha256(x).hexdigest()
roles={'reviewed_ACT':{'commit':A,'tree':'be4b5ef8960c0e9cfb9eb9ec0e1aded3a35a88df','parents':[P]},'accepted_predecessor':P,'candidate_C3':{'commit':C,'tree':'8e61ef74ad27f8ce0925fbb487ca9cf14f05fe3c'},'candidate_C2':'af39efbf32549be964cb083bd49bed6d1d5c0d2a','source_reference':{'repository':'reference/pokemon-essentials/','commit':R,'tree':'7589c800b61ba13a13040ed0d686979b80a84fd0'},'fixed_original_review':b.ORIG,'approved_PLAN':b.PLAN,'scope_proposal':'c0dc3037f6aafd736915af1d0bd920455012b30a','scope_authorization':'9503a85a122bf760f747d2b26718d3fee295bef2','own_report_commit':None,'own_report_commit_assignment':'External coordinator after mechanical publication; no self-fill or recursive containing-commit certificate.','B02_candidate_report_commit':'eee6869578f80463308ca9f2a2e618bd80c0acbe','all_candidate_report_receipts':[{'owner':x['owner'],'report_commit':x['report_commit'],'reviewed_candidate':x['reviewed_candidate'],'directory':x['directory']} for x in g['all_applicable_candidate_receipts']]}
configuration={'requested_model':'gpt-6.1-sol','requested_effort':'ultra','requested_service_tier':'default','documented_speed':'Standard','supported_interface_admission':'Task-supplied approved Plan A admission; no independent configuration probe or backend echo acquired.','effective_configuration':'UNVERIFIED','backend_certificate':None,'substitutions':0,'children_or_nested_agents':0,'other_worker_dispatch':0,'configuration_auth_quota_probes':0}
limits={'U01-U10':'RETAINED','G01-G12':'RETAINED','AX01-AX20':'RETAINED','runtime_observations':0,'proven_Demo_chains':0,'behavior_vectors_executed':0,'reference_execution':0,'screen_audio_assets_capacity_backend_validation':0,'unconditional_67_berry_full_data_obligation':False,'named_limits':['Data/Scripts.rxdata and binary/serialized data','Actual maps/events and real Demo event chains','Images/media/audio/fonts/soundfont and actual background assets/pixels/frames/timing','Executables/host DLLs/mkxp/configuration/capacity/power/host outputs','Actual plugins/dynamic dispatch/deprecated aliases/EventScene/dynamic-shadow reachability and encoded loaders','Eight cup-list references and pokemon_metrics.txt samples','Backup/gen directories; unlisted source/PBS/localization/default data ranges','Original six partially read scripts/remaining ranges,36 generation backups,7 default PBS content files,17 localization texts,one text sample,18 binary/font/resource limits'],'source_searches':'Static navigation only; neither successful searches nor ranges imply branch coverage, runtime, assets, Demo or plugin reachability.'}
# Precise all-path reading map: identities never silently become semantic reads.
paths=json.loads((OUT/'copy-and-boundary-checks.json').read_text())['actual_paths']
full_text={
 'deliverables/final-specification-set/test-catalog/engine-overworld-wp11-15-59-60.md',
 'deliverables/final-specification-set/test-catalog/pokemon-rules-wp53-60-61-62-69-70.md',
 G+'candidate-unused-placeholder',
 'review/remediation/20261003-prepare/batches/B14/candidate-3/application-1/fix-response.md',
 G+'handoff.json'}
partial_text={
 'deliverables/final-specification-set/engine-overworld/wp59-world-time-weather-field-moves.md':[[1,112],[219,270]],
 'deliverables/final-specification-set/pokemon-rules/wp60-berry-plants.md':[[48,108]],
 'review/remediation/20261003-prepare/batches/B14/candidate-3/application-1/static-checks.json':[[1,130],[155,435],[485,578]]}
logs=[]
for p in paths:
 d=b.blob(A,p); lines=d.splitlines();total=len(lines);sem=[];notes=[]
 if p in full_text:sem=[[1,total]];notes=['Complete text read; no business-domain approval inferred.']
 elif p in partial_text:sem=partial_text[p];notes=['Exact displayed/supplemented text ranges only.']
 elif p in {G+x for x in ['finding-registration.json','clause-location-bindings.json','scope-and-observation-registration.json','pre-freeze-navigation-correction.json','boundary-and-bindings.json','source-lineage.json','source-limits.json']}:
  notes=['Complete structure/primitive pointer maps acquired; original/PLAN duplicate control fields verified exactly; novel selected strings displayed. Deferred author_record/full_candidate_disposition/candidate_AREG_overlay_records/C3_successor/positive_reverse_designs and identity scalar classes are not certified as semantic reads. Full payload remains incomplete.']
 elif p in g['public_registration10']:notes=['Changed public prose partly read; exact TSV schemas/prefixes/record IDs and222 row/heading locators checked separately. Entire new field meanings not certified.']
 else:notes=['Exact payload identity acquired; complete new/copied audit meaning or original formal clauses not semantically read. Historical report identity is not current approval.']
 covered=set(i for a,z in sem for i in range(a,min(z,total)+1));unread=[];start=None
 for i in range(1,total+2):
  if i<=total and i not in covered and start is None:start=i
  elif (i>total or i in covered) and start is not None:unread.append([start,i-1]);start=None
 logs.append({**b.ident(A,p),'total_lines':total,'literal_semantic_ranges':sem,'literal_unread_ranges':unread,'semantic_complete':p in full_text,'notes':notes})
# Source ranges read in tool outputs. Static-only and no copied source retained.
sources={
 'Data/Scripts/012_Overworld/003_Overworld_Time.rb':[[1,124]],
 'Data/Scripts/012_Overworld/002_Battle triggering/001_Overworld_BattleStarting.rb':[[1,350],[351,425],[460,560]],
 'Data/Scripts/011_Battle/001_Battle/001_Battle.rb':[[1,155]],
 'Data/Scripts/012_Overworld/004_Overworld_FieldMoves.rb':[[425,515]],
 'Data/Scripts/012_Overworld/001_Overworld visuals/002_Overworld_Overlays.rb':[[1,100]],
 'Data/Scripts/012_Overworld/006_Overworld_BerryPlants.rb':[[1,195],[239,287]],
 'Data/Scripts/012_Overworld/001_Overworld visuals/001_Overworld_Weather.rb':[[210,304]],
 'Data/Scripts/010_Data/002_PBS data/018_MapMetadata.rb':[[1,100]],
 'Data/Scripts/010_Data/001_Hardcoded data/014_Environment.rb':[[1,80]],
 'Data/Scripts/001_Settings.rb':[[67,81],[470,498]],
 'Data/Scripts/011_Battle/004_Scene/002_Scene_Initialize.rb':[[90,104],[185,191]],
 'Data/Scripts/011_Battle/007_Other battle code/010_Battle_PokeBallEffects.rb':[[80,94],[185,198]]}
source_notes={'identity_policy':'Fixed reference commit only; no code execution; paths/ranges are traceability, not branch coverage.','ranges':sources,'in_scope_missing_source':['Complete settings/data/caller paths beyond the displayed ranges, including full map metadata initialization and extended backdrop consumer branches, not certified as read.','Current calendar and connected-weather evidence beyond original qualified controls/correct catalog text was not independently re-read in source; historical qualification retained without new source approval.']}
# All B14 current original-ID/contribution dispositions, including unsatisfied gate.
def aliases(v):
 z=[]
 def walk(x):
  if isinstance(x,dict):
   for k,w in x.items():
    if k=='raw_id' and isinstance(w,str):z.append(w)
    walk(w)
  elif isinstance(x,list):
   for w in x:walk(w)
 walk(v);return list(dict.fromkeys(z))
disps=[]
for i,z in enumerate(reg['dispositions']):
 o=originals[z['id']];oi=next(i for i,x in enumerate(original) if x['id']==z['id'])
 disps.append({'record_key':z['record_key'],'canonical_id':z['id'],'effective_original_priority':o['priority'],'original_aliases':aliases(o),'contribution_kind':'PRIMARY' if z['primary'] else 'SHARED','primary_owner':z['primary_owner'],'classification':z['classification'],'canonical_state':'OPEN','current_status':'INTEGRATED_PENDING_ACTUAL','B14_accepted':False,'original_control':{'commit':b.ORIG,'path':'review/global-independent-review/2026-10-03-fd82a639/findings.json','pointer':'/'+str(oi)},'qualified_acceptance':{'commit':b.PLAN,'path':'review/remediation-20261003-prepare/finding-acceptance.json','pointer':'/'+z['id']},'complete_control_fields_exact_to_original':True,'minimum_acceptance_fields_exact_to_PLAN':True,'qualified_original_reading':'All selected unique primitive values displayed; original structure/pointer mappings retained in controls maps. No omission of unique values claimed. This does not certify unread current overlays or original adjudication documents outside these complete selected objects.','current_formal_locations':[{'path':x['path'],'clauses':x['clauses'],'identity':x['identity']} for x in z['current_formal_locations']],'test_ids':z['static_test_ids_not_executed'],'candidate_sha':C,'applicable_candidate_receipts':[{'owner':q['owner'],'report_commit':q['report_commit'],'reviewed_candidate':q['reviewed_candidate']} for q in z['candidate_receipts']],'pending_contributors':z['pending_contributors'],'B02_actual_disposition':'REVIEW_GATE_UNSATISFIED_REQUEST_CHANGES','behavioral_scope_statement':'B02 has inspected complete two catalogs and bounded shared time/ordered-write evidence. This is no reapproval of unrelated whole domains or of all24 business repairs. Identity preservation supports only the named protected ranges.','remaining_obligations':z['downstream_obligations'],'current_binding':{'commit':A,'path':G+'finding-registration.json','pointer':'/dispositions/'+str(i)}})
save('contribution-dispositions.json',disps)
own=[]
for z in owner['dispositions']:
 own.append({'canonical_id':z['id'],'accepted_owner_role':z['B02_role'],'accepted_bounded_contract':z['approved_scope'],'current_owner_control_binding':b.ident(P,b.BASE+'B02/integration-stage-1/finding-registration.json'),'protection':'Unfiltered path boundary shows no B02 formal or historical-control edits. All299 engine/93 Pokemon rows outside WT/FS/BP/FP retain accepted predecessor bytes/order/multiplicity.','exact_changed_interfaces':'Shared catalog whole-file identities changed through explicitly reviewed WT/FS/BP/FP rows and WT41–44. The accepted B02 cached-tint reader remains separate from map-application and new-battle gates.','status':'PROTECTION_SUPPORTED_AS_OBSERVATION; ACT_GATE_UNSATISFIED','NOT_AFFECTED_certificate':False,'reason':'No automatic PASS transfer. Complete final integration semantic review and independent-first ordering were not completed.','remaining_owner_obligations':z['remaining_responsibility']})
save('accepted-owner-dispositions.json',own)
# Gate-local findings are about this review record, not new canonical/gameplay issues.
issues=[{'id':'R-B14-ACT-B02-REVIEW-001','severity':'GATE_BLOCKING','type':'INDEPENDENT_REVIEW_ORDER_NOT_SATISFIED','scope':'Exact ACT affected-B02 reviewer evidence','payload_defect_asserted':False,'cause':'Navigation novel-value extraction read writer self-check/satisfaction prose before first judgment was saved. The reviewer failed to defer those fields.','precise_locations':[{'commit':A,'path':G+'pre-freeze-navigation-correction.json','selector':'Writer validation/current-map/heading self-check content; prejudgment-novel-values-index.json values730–749'},{'commit':A,'path':G+'scope-and-observation-registration.json','selector':'Writer satisfaction statements; prejudgment mapping650/655/664/672/683'}],'legal_minimal_input':'Review this exact ACT with the mandated independent-first sequence, then run the recorded novel navigation extraction through value749 before creating independent-first-judgment.md.','ordered_result':['Core Git/catalog/source observations acquired','Writer self-check values displayed before receipt','First judgment subsequently saved with explicit disclosure','Independent-first requirement remains unfulfilled; exact B02 PASS cannot be certified'],'reverse_contrast':'A fresh independent reviewer reads permitted input/navigation and all required independent evidence, freezes its first judgment/receipt, then reads writer comparisons. No retroactive receipt repairs this exposure.','source_document_bindings':[b.ident(A,G+'actual-request-B02.json'),b.ident(A,G+'pre-freeze-navigation-correction.json'),b.ident(A,G+'scope-and-observation-registration.json')],'acceptance':'A compliant fresh separate B02 actual gate at this same exact ACT is necessary. This reviewer neither dispatches another worker nor requests an ACT content change merely for its own procedural failure.','evidence_limits':'Self-reported review ordering, immutable receipt and exact input pointer map. No backend/process certificate and no gameplay defect inferred.','new_canonical_root':False,'canonical_closure':False},
{'id':'R-B14-ACT-B02-REVIEW-002','severity':'GATE_BLOCKING','type':'MANDATORY_SEMANTIC_READING_INCOMPLETE','scope':'Exact ACT affected-B02 reviewer evidence','payload_defect_asserted':False,'cause':'Both complete unfiltered diff streams were acquired and inventoried, but their complete new/copied audit meanings, all relevant current owner clauses and complete integration relationships were not semantically read. Identity checks and partial dictionaries cannot discharge the gate.','precise_locations':['diff-inventory.json: every260/199 section and hunk bound; reading-log.json gives all ACT changed-path literal unread ranges','reading-log.json: unresolved current audit fields and author comparison truncation maps'],'legal_minimal_input':'Use exact full unfiltered predecessor-to-ACT and C3-to-ACT streams and compare their semantic inspection map against the mandated complete reading contract.','ordered_result':['Full streams acquired and hashed','61 C3 and155 candidate-report copies verified exactly; current hashes and72 planned reads matched','Complete catalogs and selected controls/source clauses read','Remaining semantic fields/ranges are explicitly unresolved','No PASS_SCOPED or broad NOT_AFFECTED disposition is issued'],'reverse_contrast':'Complete every in-scope required meaning with exact-identity reuse or genuinely lossless read mapping retaining all unique values and original structure; separately discharge every owner clause/caller/data/condition dependency.','source_document_bindings':[b.ident(A,G+'actual-request-B02.json'),b.ident(A,G+'current-readers.json')],'acceptance':'Complete exact B02 actual review evidence under the required order. Unread content cannot be labeled absent, harmless or NOT_AFFECTED.','evidence_limits':'The issue is the present review evidence, not a claim that ACT behavior or integration bytes are wrong. Counts/hash/parse do not substitute for semantic reading.','new_canonical_root':False,'canonical_closure':False}]
save('findings.json',{'run_id':'20261003-prepare','gate':'SEPARATE_AFFECTED_B02_ACTUAL','reviewed_ACT':A,'verdict':'REQUEST_CHANGES','quality_PASS':False,'behavioral_or_ACT_payload_findings':[],'gate_local_review_findings':issues,'complete_current_contribution_dispositions':'contribution-dispositions.json','accepted_owner_dispositions':'accepted-owner-dispositions.json','report_commit':None,'finding_closed':False})
trunc=[{'read':'Initial complete path inventory','status':'Raw tool output truncated; complete inventory retained in diff-inventory.json. Missing inventory tail supplemented from recorded sections195 onward; complete semantic diff reading not claimed.'},
{'read':'Eight public Markdown path diffs','status':'Combined output truncation left exact unconfirmed hunk content; conservatively unresolved. No public whole-meaning PASS.'},
{'read':'controls long195–246 plus short0–380','status':'Outer tool truncation supplemented short0–28 and long240–246; complete selected unique scalar dictionary read.'},
{'read':'Pokemon catalog1–100','status':'BP03–BP09 middle truncation supplemented lines48–57; full181 lines read.'},
{'read':'C3 static-checks.json','status':'Initial truncation supplemented literal155–435; conservatively current log marks131–154 and436–484 unread unless reacquired.'},
{'read':'C3 application-manifest.json','status':'Output truncated; whole1239-line file conservatively unresolved for complete semantic reading.'},
{'read':'novel1000–1272','status':'Values1117–1158 omitted by tool truncation; unresolved until supplemented. They are writer copy-check labels, not independently adopted claims.'},
{'read':'Public heading diagnostics','status':'Initial own test omitted line terminators and falsely flagged heading hashes. Corrected to full-line byte hashing; all222 locators match. Truncated false-failure listing has no quality meaning and is not retained as a finding.'}]
reading={'run_id':'20261003-prepare','reviewed_ACT':A,'complete_mandatory_reading':False,'independent_first_order_compliant':False,'all_changed_paths':logs,'fixed_original_control_reading':{'original':b.ident(b.ORIG,'review/global-independent-review/2026-10-03-fd82a639/findings.json'),'PLAN':b.ident(b.PLAN,'review/remediation-20261003-prepare/finding-acceptance.json'),'selected_ids':json.loads((OUT/'control-selection.json').read_text())['ids'],'unique_values':1833,'long_value_display_ranges':[[0,246]],'short_value_display_ranges':[[0,1587]],'supplements':'Truncated outer call supplemented short0–28 and long240–246. Exact mappings and structure retained; fixed objects retain original values.','whole_global_233_objects_read':False,'scope':'35 complete selected objects: B02 twelve and B14 twenty-four overlap C003. Unrelated whole-domain approval not repeated.'},'current_registration_selected_values':{'index':'prejudgment-novel-values-index.json','displayed_ranges':[[0,1116],[1159,1271]],'unread_values':[[1117,1158]],'identity_vs_semantics':'Non-string, pure identity/path and deferred object classes are not certified as semantic reads; full audit coverage remains incomplete.'},'fixed_source':source_notes,'additional_ACT_literal_reads':[{'path':'deliverables/final-specification-set/generic-kernel/wp06-time-random-steps-stats.md','ranges':[[1,139]]},{'path':'deliverables/final-specification-set/combat-requirements/wp39-battle-context-and-participants.md','ranges':[[234,242]]},{'path':b.BASE+'B09/acceptance-stage-1/report-corrections-successor.json','ranges':'FULL; accepted report-only correction, no fresh B09 business approval'}],'truncation_and_supplement_log':trunc,'all_identity_checks':'hash-validation.json; planned-read-identity-checks.json; copy-and-boundary-checks.json; public-registration-checks.json','full_diff_reproduction':'diff-inventory.json; no path exclusion; no private raw-diff archive duplicated','limits':limits}
save('reading-log.json',reading)
allids={}
for row in json.loads((OUT/'hash-validation.json').read_text()):
 ob=row['observed'];allids[(row['commit'],row['expected']['path'])]={'commit':row['commit'],'path':row['expected']['path'],**ob}
for p in paths:allids[(A,p)]=b.ident(A,p)
for c,p in [(b.ORIG,'review/global-independent-review/2026-10-03-fd82a639/findings.json'),(b.PLAN,'review/remediation-20261003-prepare/finding-acceptance.json'),(P,b.BASE+'B02/integration-stage-1/finding-registration.json'),(P,b.BASE+'B02/integration-stage-1/integration-manifest.json')]:allids[(c,p)]=b.ident(c,p)
save('input-identities.json',{'identity_roles':roles,'requested_configuration':configuration,'object_identities':list(allids.values()),'identity_checks_do_not_imply_semantic_reading':True})
designs=[{'id':'B02-ACT-D01','classification':'Generic Kernel; Engine / Overworld Integration','input':'Cached18:00 tone at runtime100; host clock18:30 stable; setting enabled; read at129.999 then130; no cache/state rewrite.','ordered_expected':'129.999 retains cached18:00;130 recomputes host18:30 interpolation and updates refresh timestamp.','reverse':'Disable shading: existing cache returned without refreshing timestamp; cold cache zero is separate.','bindings':[{'ACT_path':'deliverables/final-specification-set/generic-kernel/wp06-time-random-steps-stats.md','lines':[41,50]}, {'reference_path':'Data/Scripts/012_Overworld/003_Overworld_Time.rb','lines':[73,124]}]},
{'id':'B02-ACT-D02','classification':'Engine / Overworld Integration; Combat Requirements','input':'Ordinary valid new battle; able player, nonempty legal parties/opponents, valid dependencies; map scene/metadata nonCave,indoor,shadingtrue,stable20:00; separate legal tint target operation; no skip/interception/plugin/external/time mutation.','ordered_expected':'Tint operation writes neutral; preparation assigns new-battle time2.','reverse':'Outdoor-only opens tint gate but time remains2. NonCave shadingfalse retains new-battle default0. MetadataCave forces2 before shading even with explicit valid Grass battle environment. Shadingtrue17/12 gives1/0 for both outdoor flags.','bindings':[{'ACT_path':'deliverables/final-specification-set/engine-overworld/wp59-world-time-weather-field-moves.md','lines':[63,98]},{'ACT_path':'deliverables/final-specification-set/test-catalog/engine-overworld-wp11-15-59-60.md','lines':[360,363]},{'reference_path':'Data/Scripts/012_Overworld/002_Battle triggering/001_Overworld_BattleStarting.rb','lines':[209,304]},{'reference_path':'Data/Scripts/011_Battle/001_Battle/001_Battle.rb','lines':[98,115]}]},
{'id':'B02-ACT-D03','classification':'Engine / Overworld Integration; User Interface','input':'Legal direct FLY D=(M,7,5), creature/resources/transfer/BGM/refresh normal, E nonempty,countN; callback performs no related state mutation but throws ordinary exception; fade cleanup normal.','ordered_expected':'CountN+1 and down-facing landing/music/refresh committed; wait unrequested;E/D clears and normalreturn unreached;E/D retained,error propagated. A later window result needs its own lawful undisposed update opportunity.','reverse':'Absent or normal nonmutating callback plus normal tail reaches wait→clearE→clearD→true; delayed window may then reset clock and inspect later gates.','bindings':[{'ACT_path':'deliverables/final-specification-set/engine-overworld/wp59-world-time-weather-field-moves.md','lines':[245,262]},{'reference_path':'Data/Scripts/012_Overworld/004_Overworld_FieldMoves.rb','lines':[471,512]},{'reference_path':'Data/Scripts/012_Overworld/001_Overworld visuals/002_Overworld_Overlays.rb','lines':[4,45]}]},
{'id':'B02-ACT-D04','classification':'Pokémon Rules','input':'PlantedOLD first life,base3h,GROWTHMULCH,duration0/stage1,lastT−32400,currentintegerT,validRain category;positiveelapsed,no replant/otherrelatedwrite; explicit settlement.','ordered_expected':'Stage duration8100; common duration32400→stage5→timestampT before old watering and before new drying.','reverse':'Unplanted/nonpositiveelapsed return before common writes; replant-limit reset earlierreturn separate; no-mulch9h stage4; ordinaryOLD display does not settle.','bindings':[{'ACT_path':'deliverables/final-specification-set/pokemon-rules/wp60-berry-plants.md','lines':[67,98]},{'reference_path':'Data/Scripts/012_Overworld/006_Overworld_BerryPlants.rb','lines':[97,160]}]},
{'id':'B02-ACT-D05','classification':'Engine / Overworld Integration','input':'StableRain category strength60,oddindex1 visible with valid bitmap,no fade; expiry reset sampleslife.40.','ordered_expected':'Reset visible/opacity255 thenreturn, no ordinary hiding in samecall.','reverse':'Independent ordinary nonreset remaining.30/.19 gives0/255; even0 drop; no pixel/frame claim.','bindings':[{'reference_path':'Data/Scripts/012_Overworld/001_Overworld visuals/001_Overworld_Weather.rb','lines':[210,304]},{'ACT_path':'deliverables/final-specification-set/test-catalog/engine-overworld-wp11-15-59-60.md','lines':[350,351]}]}]
for x in designs:x['status']='UNEXECUTED_STATIC_DESIGN';x['reference_commit']=R;x['ACT_commit']=A;x['evidence_limits']='Source/document reasoning only. No runtime, assets, screen/audio, capture probability, Demo/plugin reachability or backend validation.'
save('static-designs.json',{'reviewed_ACT':A,'designs':designs,'behavior_vectors_executed':0,'runtime_observations':0,'catalog_preservation':'catalog-preservation.json','no_reference_behavior_execution':True})
prior=[{'id':'B14-AFFECTED-B03-001','priority':'P2','origin':'B14 normal-tail premise omission','scoped_source_observation':'Supported by fresh Field471–512/Overlays4–45 and ACT WP59/WT28/39/40','ACT_gate_disposition':'NO_INDEPENDENT_PASS; review-order/coverage exception remains','remaining_limits':'Lawful later update separate; no normal-menu optional callback reachability/continued game claim'}, {'id':'R-B14-1-001','priority':'P3','origin':'Retained timestamp-order residue','scoped_source_observation':'Fresh Berry97–160 and ACT BP18/berry§5.2 agree','ACT_gate_disposition':'NO_INDEPENDENT_PASS','remaining_limits':'Unplanted/nonpositive/replant-limit exclusions; OLD display/OLD UI distinction;67-data condition'}, {'id':'B14-B04-R1-01','priority':'P2','origin':'Retained splash sentence residue','scoped_source_observation':'Fresh Weather210–304 and ACT WT31 agree; original/finalWP16 copy identity checked but sentence not yet separately read','ACT_gate_disposition':'REVIEW_INCOMPLETE; NO_PASS','remaining_limits':'Reset255 versus ordinary<.2; no frame/pixel'}, {'id':'B14-AFFECTED-B09-001','priority':'P3','origin':'Retained tint/battle-time cross-reference; contextualC007/shared003; no newroot/regression','scoped_source_observation':'Fresh source/new-battle prerequisites and ACT finalWP59§3.5/WT41–44 support distinctgates; WP39§7.3 read and byte-preserved. Original counterpart identity checked, not fully read.','ACT_gate_disposition':'NO_INDEPENDENT_PASS','remaining_limits':'Stableclock,separate tint/preparation, validbattle, ableplayer/opponents/dependencies, exclusions and no effect/media/capture claim'}, {'id':'FISHING15_VERSUS16','classification':'HISTORICAL_REPORT_ONLY_CORRECTION','disposition':'Original qualifiedC003 retained; FS16 text read. Old report immutable; full source/event not reapproved'}, {'id':'B09_G_ACCEPTED_REPORT_CORRECTIONS','classification':'ACCEPTED_REPORT_ONLY_QUALIFICATION','disposition':'Complete accepted successor read; boxedA=Y/liveBempty,one restoration; liveuser0,faintednear2/noreserve,livefar4 selected/registered then rejected by unchanged-state normalresolution; noPP/effect/message;B033separate. No B09 actual PASS supplied'}, {'id':'R-B14-C3-EVID-001/002/003','classification':'HISTORICAL_REPORT_ONLY_QUALIFICATION','disposition':'Current registration/errata qualifications read: candidate matching notcache;duration0→connected20 notintensity/rebuild;06:30brightness138/noon255. Old report bytes checked as copy; complete historical report contents not read and not approval.'}]
save('prior-observation-dispositions.json',prior)
(OUT/'author-comparison.md').write_text('''# Author comparison — qualified incomplete comparison

The exact reviewed ACT is `d48197f365c39925f795c1d325988c0d74e59979`. The immutable first-judgment receipt is `first-judgment-receipt.json`. It explicitly discloses premature writer-metadata self-check exposure; this document does not retrospectively certify independence.

After the receipt, the complete C3 `application-1/fix-response.md`, portions of `static-checks.json` and `application-manifest.json`, and complete AREG-G `handoff.json` were read. The application manifest was truncated and is not certified complete. AREG-G `conflict-and-validation.json` remains semantically unread. Complete current audit comparison is consequently incomplete.

The author claims distinct tint/new-battle gates, unchanged WP59§3.6/WP39§7.3,505 preserved rows plus4 additions, and the three prior repairs. Fresh source/catalog/selected-clause evidence supports the narrowly recorded observations in `static-designs.json`; exact copy/hash/row checks independently corroborate preservation identities. These observations do not inherit candidate PASS and do not certify every author claim.

The historical application/hand-off null ACT values and pending future labels describe their payload-freeze time. The external ACT identifies the current snapshot; no containing-commit self-hash is required. Writer xhigh and reviewer ultra are different requested roles; this reviewer records ultra/default Standard with backend UNVERIFIED. No alternate profile or backend certificate is inferred.

Author counts, public pending labels, and mechanical checks do not cure this review's order violation or missing semantic coverage. The final B02 actual verdict remains REQUEST_CHANGES on review evidence. No ACT behavioral content edit, canonical addition/closure, acceptance or downstream release is authorized by this comparison.
''')
summary='''# Exact ACT affected B02 review

**REQUEST_CHANGES — the B02 actual gate is not discharged.** This report records failures of the present review's independent-first ordering and semantic completion. It does not assert an ACT behavioral defect and must not be counted as an actual PASS.

Reviewed ACT `d48197f365c39925f795c1d325988c0d74e59979`, tree `be4b5ef8960c0e9cfb9eb9ec0e1aded3a35a88df`, parent/accepted predecessor `1e6b11a47370f1c7c4659a32443fc1afda597bac`. Candidate C3 `c06db6cd964188b3c693a9b7820e3a8aaffe0b04`, tree `8e61ef74ad27f8ce0925fbb487ca9cf14f05fe3c`. Fixed reference `8c5911e4a4b07b07e832e4bb0d5d8859e88b4a9b`, tree `7589c800b61ba13a13040ed0d686979b80a84fd0`. Original qualified review `93e10babe0b9c9ef8b3f5277754541b447beeeb4`; PLAN `41fffb540c6483f5296ea0d33b789b75180d27ed`. This report's commit is externally assigned after publication and remains null here. Report SHAs are separate from reviewed SHAs.

PASS_SCOPED would mean this exact ACT meets the complete bounded B02 affected contract: protected portions of both shared catalogs, complete current relevant qualified original/owner controls, clause/caller/data/condition relationships and integration/public bindings, with required independent-first sequencing and complete semantic inspection. It would not accept B14 or replace the seven other actual gates. REQUEST_CHANGES means that exact scoped gate cannot be discharged on the present evidence, whether because of a supported scoped payload issue or an explicit review-evidence failure. This report takes the latter route.

`R-B14-ACT-B02-REVIEW-001`: writer self-check/satisfaction prose was displayed from current navigation records before the first judgment receipt. The reviewer failed to defer those fields. The receipt preserves the disclosure; it cannot undo exposure. `R-B14-ACT-B02-REVIEW-002`: full unfiltered stream acquisition, parse/hash checks and partial value dictionaries did not become complete semantic reading. Every changed path's unread literal ranges and partial-field limitations are listed in `reading-log.json`. No unread material is declared harmless or NOT_AFFECTED. A compliant fresh separate exact B02 gate remains necessary; this report dispatches nobody.

Completed independent preservation observations:

- Both full unfiltered diffs acquired with no-ext-diff/no-textconv/no-renames/binary/full-index/no-color and no exclusion. Predecessor→ACT:96,116,311bytes,SHA256 `1f88e677993c91905b72b747b187f6e94a52881178b08716fe6791bd6cbab444`,260 sections. C3→ACT:95,127,902bytes,SHA256 `5d639c30c53bb37035d2d133b715da5cc5c706afd13d278c8a7ad718368da5d9`,199 sections. Full path/hunk/index identities and reproduction parameters are in `diff-inventory.json`; raw audit provenance was not republished as a full diff archive.
- ACT has exactly61 C3 copies:12 formal(five original,seven final) and49 evidence;155 exact files from all eight supplied candidate-report directories;34 new G records;ten authorized public changes. No unexpected path or unequal copied file was found. This establishes identities, not semantic quality.
- All140 current-hash rows and72 planned current/fixed input identities match. Fixed original-review inputs retain their external commits. All222 registered heading/row positions and hashes match full original line bytes including terminators. An initial own omitted-terminator diagnostic was corrected and produced no payload finding.
- Both public TSVs retain their exact accepted header/schema/column order and170-row prefix, then append24 canonical-ID contribution records in current registration order:19 primary,five shared. There are194 public records,170 accepted and24 pending; new rows remain OPEN and bind C3 candidate receipts, with blank actual reviewed/report identity fields. All24 qualified-control/minimum-acceptance projections match original/PLAN fields. Semantic approval of all current nested obligations remains incomplete.
- Both catalogs were read in full. ACT361 engine+148 Pokemon=509; all505 C2 old rows retain bytes,terminators,order,multiplicity; fourWT41–44 are appended. Second catalog wholly equalsC2. All299 engine and93 Pokemon rows outsideWT/FS/BP/FP preserve accepted predecessor sequence. Accepted B02 formal/history and unaffected B01–B09 bytes lie outside the unfiltered change boundary; no old B09-G freeze/report was altered.

The bounded time-reader observation has fresh source support: cached tint recomputes only at its runtime30-second gate; map tint applies outdoor/map-scene/shading gates; ordinary new battle begins withtime0 and preparation tests map-metadataCave before shading. Indoor nonCave/shadingtrue20:00 gives neutral tint/time2; outdoors changes tint eligibility only; nonCave/shadingfalse retains default0; metadataCave forces2 despite legal explicitGrass;17/12 gives1/0 with either outdoor flag. Legal ordinary creation excludes debug skip/interception/plugin/external/time rewriting and requires able player,valid opponents/nonempty parties and normal dependencies; tint/preparation observations and stable clock remain separate. Correct WP59§3.6 and WP39§7.3 stay protected. WT41–44 are unexecuted.

Fresh source also supports FLY callback exception prefix/unreached tail and separately lawful later window update, common berry timestamp before watering/drying with early-return exclusions, and splash reset255/early-return versus ordinary remaining<0.2. Current document reading for these observations is explicitly partial where noted; no complete original/final counterpart approval is fabricated. `prior-observation-dispositions.json` retains the four existing IDs/priorities/origins, fishing15/16 correction, accepted B09 fixture qualification with separateB033 residual, and the three historical-only C3 evidence qualifications. These do not add canonical roots or change correct formal behavior.

Complete current24 contribution and accepted12 B02 owner dispositions are in `contribution-dispositions.json` and `accepted-owner-dispositions.json`. Every current B14 entry remains INTEGRATED_PENDING_ACTUAL/unaccepted; no business repair is accepted from equal blobs or a historical PASS. The all-eight exact actual gates(FULL,B02,B03,B04,B06,B07,B08,B09) remain mandatory before AREG-C. B10 remains blocked, then refreezes53 reads/eight writes/contract after acceptance; later WP46 reverse obligations remain.

Accepted statistics remain9/21,170 records,142 touchedIDs,109 primaryIDs, minimum109 satisfied, strict100 satisfied+nine pending,229 OPEN/0 CLOSED; B14 unaccepted24/19. The seven classifications remain Generic Kernel,Creature-RPG,Pokémon Rules,Combat Requirements,Engine / Overworld Integration,User Interface,Demo / Developer Experience. U01–U10/G01–G12/AX01–AX20 and all named binary/serialized/map/event/media/resource/host/plugin/configuration/sample/backup/gen limits remain. No unconditional67-berry full-data obligation. Runtime observations0,provenDemo0,behavior vectors executed0; no reference/compiler/converter/generator/deserializer/simulator/historical-verifier execution or framework/API/adapter work.

Requested reviewer configuration gpt-6.1-sol/ultra/default documented Standard; effective configuration UNVERIFIED under approved Plan A. No backend certificate,probe,alternate profile,child/nested agent,other worker dispatch,Git index/ref mutation,publication or acceptance. Only this new report directory was written. Coordinator may mechanically publish this report, but it is an actual-only non-PASS handoff.
'''
(OUT/'report.md').write_text(summary)
save('review-manifest.json',{'run_id':'20261003-prepare','role':'Fresh independent exact-ACT affected B02 reviewer','gate':'SEPARATE_AFFECTED_B02_ACTUAL','verdict':'REQUEST_CHANGES','actual_PASS':False,'identity_roles':roles,'configuration':configuration,'scope':g['bounded_interface'],'fresh_full_WP39_WP40_required':False,'complete_original_and_owner_controls_required':True,'first_judgment_receipt':'first-judgment-receipt.json','independent_first_order_compliant':False,'complete_semantic_reading':False,'finding_file':'findings.json','current_contribution_dispositions':'contribution-dispositions.json','owner_dispositions':'accepted-owner-dispositions.json','prior_observations':'prior-observation-dispositions.json','all_eight_actual_gates_mandatory':g['all_gates_required_before_AREG_C'],'AREG_C_acceptance':False,'B14_accepted':False,'canonical_OPEN':229,'canonical_CLOSED':0,'accepted_statistics':{'batches':'9/21','contribution_records':170,'touched_IDs':142,'primary_IDs':109,'minimum_satisfied':109,'strict_satisfied':100,'strict_pending':9,'B14_pending':24,'B14_primary':19},'public_records':194,'limits':limits,'write_scope':b.BASE+'B14/affected-B02-actual-review-1/','Git_mutations':0,'report_publication':'External coordinator only','new_canonical_numbering':False,'no_self_hash_or_containing_commit_recursion':True})
print('Required report artifacts written; exact gate REQUEST_CHANGES, no actual PASS.')
