"""New report writing and static document validation only; no reference behavior execution."""
import pathlib,json,hashlib,re,datetime
from read_bookkeeping import get,ACT,PRE,REF
from semantic_bookkeeping import ORIG,PLAN
D=pathlib.Path(__file__).parent
G='review/remediation/20261003-prepare/batches/B14/integration-stage-1/'
C3='c06db6cd964188b3c693a9b7820e3a8aaffe0b04'
def read(n):return json.loads((D/n).read_text())
def save(n,v):(D/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
def digest(b):return hashlib.sha256(b).hexdigest()
def identity(c,p,role,ref=False):
 b=get(c,p,ref);return dict(commit=c,path=p,role=role,git_blob=hashlib.sha1(b'blob '+str(len(b)).encode()+b'\0'+b).hexdigest(),sha256=digest(b),bytes=len(b))
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
receipt=read('first-judgment-receipt.json');assert digest((D/'independent-first-judgment.md').read_bytes())==receipt['sha256']
snap=read('preliminary-turn-1/snapshot-receipt.json')
# The immutable first judgment and preliminary copies are never rewritten.
checks=read('completion-pointer-relationship-checks.json');assert not checks['errors'] and all(x['passed'] for x in checks['checks'])
pages=read('completion-business-page-index.json');events=[json.loads(x) for x in (D/'completion-display-receipts.jsonl').read_text().splitlines()]
assert {x['page'] for x in events if x.get('mode')=='audit_business'}>=set(range(len(pages['pages'])))
formal=read('completion-formal-map.json');franges=[(x['first'],x['last_exclusive']) for x in events if x.get('mode')=='formal'];assert all(any(a<=i<z for a,z in franges) for i in range(len(formal['semantic_units'])))
assert read('hash-and-control-checks.json')['hash_table_findings']==[]
assert read('navigation-identity-checks.json')['errors']==[]
owner_reason={
'GIR-FD82-003':'Fresh full WP39/WP40 retain distinct participant and command roles, actual partner ownership/shared creature identities and ordered failures. Current WP59 capability/display phases and berry plot state impose no source hierarchy or container layout. The new time suffix adds only an independent consumer condition; the accepted §3.5 participant sharing and sole terminal restoration remain observable requirements.',
'GIR-FD82-005':'Fresh WP40§4.3/CM-31 plus selection, command registration, numeric target resolution and Eevee/HelpingHand data preserve live user0, fainted near2 without reserve and live far4. Object-valued initial matching chooses4; nil text/member highlight is separate from unselected button. USE registers4; unchanged numeric nearness rejects it later. No PP/effect/message conclusion. B033 no-live-nonself fallback is separate.',
'GIR-FD82-A047':'WP42§4.2/G11–12 preserve integer division before the real level factor and the zero-share early return after EV. New WP59 tint/time conditions and fishing request outcomes do not change growth inputs, distribution owner segments, experience settings or integer checkpoints. Growth may follow capture but is a distinct preserved step.',
'GIR-FD82-A049':'WP42§4.3/G10/G13 preserve direct single-creature summary, four old plus one new move, cancel/retry and committed growth before learning. Current B14 field presentation and clock observations introduce no party-selection layer or rollback of this learning caller.',
'GIR-FD82-A059':'Fresh WP39§7.5/BC23–25 retain separate wild/trainer battle/victory/capture audio selections, ordered fallback and preset precedence. FLY refresh/music precede its optional callback; that travel request does not redefine battle audio fields, clear presets or prove actual audio.',
'GIR-FD82-B001':'Fresh full WP40§5.2/CM15–16/30 preserve pre-PP failure record clearing versus later no-target PP consumption, including special-use differences. The time/background preparation suffix and world daily gate do not insert a command success check or change these execution checkpoints.',
'GIR-FD82-B002':'Fresh WP39§4.3/BC19–20 retain nonempty constructor prerequisites and missing owner-count failures before ordinary no-able messages, with committed creation prefix. WT41–44 require valid able entry; they do not use or normalize this invalid-owner case or promise rollback.',
'GIR-FD82-B003':'Fresh WP39§7.1/BC21 retain all14 exact rule literals and the three consumer-only clauses. Current Cave metadata precedes shading independently of explicit valid battle environment; it does not invent rule aliases or conflate sleep and sleepclause.',
'GIR-FD82-B005':'WP39/40 full, WP41§5.1/SW09 and CP01/24 preserve complete internal trainer/single-seat/switch-style/able-reserve/prompt gates, command order, priority keys and capture critical versus ordinary paths. B14 ordinary new-battle designs exclude skip/interception and make no capture-probability claim; fishing outer true is not battle victory or successful capture.',
'GIR-FD82-B006':'Fresh full WP40§5.6/§10 and CM02/33 retain default ANY=false/FOREIGN=true, high-level ownership matrix and prior guards. B14 shading is a separate configuration read; it does not modify obedience configuration or convert special use into guaranteed obedience.',
'GIR-FD82-B007':'WP38§4/CP10/23 preserve effective battle weight in0.1kg, valid ability/item suppression and Heavy Ball thresholds/zero-rate early return. WP59§3.5 only corrects a time consumer reference; Dusk Ball reads time2 separately, and fishing encounter identity does not become a weight modifier.',
'GIR-FD82-B008':'Fresh WP40§4.2/CM19–20/32 retain direct-use effect-existence qualification, default eligibility, committed inventory consumption and no generic refund. Field capability/rod outer returns are genuine separate entry results; no shared success or refund guard is inferred.',
'GIR-FD82-B009':'Fresh WP39§3.2/BC22 preserve trigger-type2 versus0 under the complete event/interpreter/distance/candidate premises. B14 completed-step generic notifications and forced/interpreter early return do not alter that trainer-event classification or prove a Demo chain.',
'GIR-FD82-B011':'WP42§5.1–5.2/R04 preserve formal fainting cleanup before the stage14 early exit and skipped later wall/round-marker tail. The WP61 ordinary transfer/poison handled gate and B14 FLY exception tail are different callers; neither implies a global rollback or automatic battle end-phase cleanup.',
'GIR-FD82-B012':'WP41§6/SW28 preserve manual Shift action cost, Fury Cutter reset, counter damage retention and index remapping. New time rows inspect creation and tint without repositioning; NearAlly rejection requires unchanged layout/life and cannot borrow the later automatic-adjustment phase.',
'GIR-FD82-B013':'WP39 participant identity, WP38§§5–6, WP42§6 and WP20§6.4 plus CP20–22/E14/CX40–42 preserve actual partner participation and old merged identities. Normal receive shifts player records while storage retains A; the sole terminal restoration yields boxedA=Y/liveBempty before outer healing/pickup. Registered-only partner and synchronized no-partner reverse remain distinct.',
'GIR-FD82-B014':'WP41§8/SW29 retain actual successful-hit count separate from HP loss, with living user/opponent/legal reserve gates. B14 tint opacity and presentation resource observations are independent of combat damage and do not rewrite this zero-HP-loss pivot condition.',
'GIR-FD82-B015':'WP39§6.1/WP42§5.1/R10 preserve saved future-source identity, off-field source crossing cleanup of current living relations before attack and the still-in-field contrast. Daily virus decrement samples current party status; it does not redefine battle participant or saved-source identity.',
'GIR-FD82-B025':'WP42§3.2/R08/R11 retain Perish Song saved source rather than last mover, clause checkpoints and possible later ordinary judge reassignment. B14 partial-write descriptions and outer return contracts do not promote an intermediate decision into irreversible victory.',
'GIR-FD82-D018':'WP42§5.1/§5.4/R09 preserve full pre-adjustment candidate collection, owner restriction, two-seat total-plan guard and later plan-order execution. WT41–44 end at preparation, and the NearAlly fixture excludes later repositioning; neither changes the current distribution or this later phase.'}
owner=read('owner-dispositions.json')
for r in owner['dispositions']:
 r['current_role_disposition']='PRESERVED_B09_SCOPED_SUPPORTED_AT_EXACT_ACT'
 r['changed_clause_caller_condition_comparison']=owner_reason[r['id']]
 r['current_preserved_owner_input_commit']=ACT
 r['accepted_projection_exact_to_predecessor']=True
 r['fresh_semantic_evidence']='reading-log.json#display_receipts and #completion; current named clauses/catalog rows, not prior PASS transfer'
owner['quality_gate_complete']=True;owner['B033_residual']=dict(id='GIR-FD82-B033',disposition='SEPARATE_OPEN_RESIDUAL_OUTSIDE_B09_CONTRIBUTION_ACCEPTANCE',original=ORIG,PLAN=PLAN,complete_objects_read=True,qualification='No living nonself same-side member is the fallback condition; live far4 belongs to005. No new repair, root or closure.')
save('owner-dispositions.json',owner)
contribution_reason={
'GIR-FD82-002':('BOUNDED_DEPENDENCY_SUPPORTED','WP59§5.7/§7 retain FLY normal/throwing tails and separately lawful location-window update. WP39 ordinary creation remains valid only after its own entry gates; retained destination does not certify resumed gameplay or new battle.'),
'GIR-FD82-003':('BOUNDED_AFFECTED_SUPPORTED','Neutral capability/plot/handled-state terms preserve WP39§3.5 sharing, WP38 receive, WP42 one restoration and WP40 registered target anomalies. C3 time separation adds behavior, no future source container architecture.'),
'GIR-FD82-C003':('BOUNDED_AFFECTED_SUPPORTED','WT41–44 supply ordinary valid entry and separate time observations; FS16 valid event and FP daily infected non-egg gate remain qualified. WT07 enter0→connected20 is duration, not intensity; capture propagation remains a separate fixed-source chain.'),
'GIR-FD82-C007':('BOUNDED_AFFECTED_SUPPORTED','Full hourly channels/cache retain their identities; current WP59§3.5 separates tint from new-battle time and preserved WP39§7.3. Indoor20/shading-off/Cave-first/17–12 contrasts are decisive; no unconditional67 berry data or pixel/capture promise.'),
'GIR-FD82-C086':('NOT_AFFECTED_B09_SUPPORTED','WP59§5.3/§5.7 direct ascent/menu surfacing has its own terrain/map/return/music/count conditions. It changes world travel before any later legal battle; current WP39§3/§7.3 independently samples the resulting map and retains entry gates, participant identities and preparation precedence.'),
'GIR-FD82-C087':('NOT_AFFECTED_B09_SUPPORTED','WP59§5.3 preserves full four facing-event markers and qualification; none is a battle participant/owner/target rule. Current WP39§3.2 trainer trigger conditions and BC22 are unchanged; event marker containment is not Demo or battle reachability.'),
'GIR-FD82-C088':('BOUNDED_DEPENDENCY_SUPPORTED','Travel coordinates/directions and committed FLY prefix differ by entry. Optional callback normal/absent versus throwing paths are explicit; outer true does not mean battle victory. WP39 creation remains a distinct later caller.'),
'GIR-FD82-C089':('NOT_AFFECTED_B09_SUPPORTED','WP59§5.6 describes field presentation phases, no-individual false and qualified completion/resources. WP39§7.3 sampled battle context and WP40 command contracts are unchanged; graphical/input opportunities are not guaranteed map updates or combat success.'),
'GIR-FD82-C091':('NOT_AFFECTED_B09_SUPPORTED','WP59§3.3 compares calendar candidates and independently writes localized names/refresh. WP39§7.3 reads hour predicates for battle preparation, not calendar candidate/name cache; its sampled context and all B09 owner clauses remain exact.'),
'GIR-FD82-C092':('BOUNDED_DEPENDENCY_SUPPORTED','WP16§5.1.1 single splash sentence/WT31 separates reset255+return from nonreset<.2; WP59 weather display gates remain distinct from WP39 sampled battle weather/time. No background/frame guarantee or change to battle participant rules.'),
'GIR-FD82-C093':('NOT_AFFECTED_B09_SUPPORTED','WP59§4.1/§4.5 retains nine weather resource/velocity/tone identities and display guards. WP39§7.3 weather sampling and battle environment mapping remain preserved; overworld particle resources do not certify battle backdrop assets or audio.'),
'GIR-FD82-C094':('BOUNDED_DEPENDENCY_SUPPORTED','WP59§4.3 enter0 then connected caller duration20 and display guards are current. WP39§7.3 samples map weather at preparation; duration20 is not intensity or a changed battle weather rule. Explicit transfer differs from connected crossing.'),
'GIR-FD82-C095':('NOT_AFFECTED_B09_SUPPORTED','WP59§5.3/§5.7 waterfall direction/crest/menu/direct conditions preserve true-without-start. WP39 valid ordinary battle entry and WP42 outer return versus outcome remain unchanged; field effect true does not start or win a battle.'),
'GIR-FD82-C097':('NOT_AFFECTED_B09_SUPPORTED','WP59§5.8/WP61§7.1 escape record production/consumption/clear precede presentation. WP42§7 world healing/pickup and WP39 context retain their bounded independent calls; an escape record is neither participating party nor battle return result.'),
'GIR-FD82-C098':('BOUNDED_AFFECTED_SUPPORTED','Current fishing§3.1 source-square outward passage and facing fishability are separate; three rods share this gate, surfing exemption retained. Eligibility/bite/candidate/battle outcomes stay separate and WP39 ordinary creation remains unchanged.'),
'GIR-FD82-C099':('BOUNDED_DEPENDENCY_SUPPORTED','Fishing§4 input-before-strict-timeout/equality and AUTO_HOOK input premises are explicit. Rod outer normal true still differs from bite/encounter/start results; WP39 entry and WP42 victory/capture decisions are independent.'),
'GIR-FD82-C100':('NOT_AFFECTED_B09_SUPPORTED','Berry§5.2 common lifetime→stage→timestamp precedes mechanism watering/drying; stored mulch/OLD display/replant exits remain separate. WP39 new battle time samples current local hour independently, and WP42 growth/receiving owner inputs do not consume berry plot timestamps.'),
'GIR-FD82-C101':('NOT_AFFECTED_B09_SUPPORTED','Berry§6.2 moisture/once-stage writes and current-config one feedback preserve frozen mechanism distinction. Current WP20/WP39 creature/participant state and WP40 command selection do not consume plot watering feedback or adopt a double result.'),
'GIR-FD82-C102':('NOT_AFFECTED_B09_SUPPORTED','Berry§5.3 requests sparkle only for new mechanism changed old>0/new nonzero≤5; empty-ground exclusion retained. B09 battle preparation/render consumer remains separate, with no pixel or capture consequence from this field animation request.'),
'GIR-FD82-C103':('BOUNDED_DEPENDENCY_SUPPORTED','WP61§3.1–3.2 generic any-mover soot erasure and capped actual collection precede/stand apart from ordinary player encounter eligibility. Source completion/post-step guard and current WP39 entry preserve no automatic battle claim.'),
'GIR-FD82-C104':('BOUNDED_AFFECTED_SUPPORTED','WP61 qualified actual forced/interpreter completion has two generic notices then early return, skipping global/player/encounter chain. Ordinary post-step requires its own event/menu/able/encounter gates; it does not redefine accepted WP39 event kinds or imply battle reachability.'),
'GIR-FD82-C105':('NOT_AFFECTED_B09_SUPPORTED','WP61 battery warning suppresses while in battle before latch/message and depends on discharge/temporary-state conditions. WP40 command and WP39 participant/time rules remain exact; host power/capacity and clock behavior are unverified.'),
'GIR-FD82-C106':('NOT_AFFECTED_B09_SUPPORTED','WP59 cave record/presentation geometry/tone restore requests do not equal Cave map metadata. New-battle Cave-first time derives from metadata, not cave animation or completed tint; WP39§7.3 remains protected and resources unobserved.'),
'WP80-INTAKE-R01':('NOT_AFFECTED_B09_SUPPORTED','WP59§4.2 keeps ASCII Weather separator and valid data identity; original already correct. WP39§7.3 consumes valid compiled metadata as a premise, without compiler execution, parser redesign, alias scope expansion or new combat behavior.')}
con=read('contribution-dispositions.json')
for r in con['dispositions']:
 r['disposition'],r['reason']=contribution_reason[r['id']]
 r['scope']='B09 affected interface and current integration registration only; no independent full24 business-domain approval'
 r['preserved_B09_inputs_commit']=ACT
 r['current_source_binding']=REF
 r['independent_ACT_gate_complete']=True
con['verdict']='PASS_SCOPED_B09_INTERFACE_ONLY';save('contribution-dispositions.json',con)
prior=read('prior-observation-dispositions.json')
for r in prior['observations']:
 r['disposition']='HISTORICAL_REPORT_ONLY_QUALIFICATION_PRESERVED' if r['id'] in prior['historical_report_only_ids'] else 'SATISFIED_OR_PRESERVED_IN_B09_EXACT_ACT_SCOPE'
 r['reviewed_actual']=ACT;r['evidence_limits']='Static independent document/source/caller/qualification assessment; all designs unexecuted, no canonical closure or acceptance.'
prior['B033']='Complete original/PLAN residual read; separate OPEN future-owner scope, not additional B14 repair.';save('prior-observation-dispositions.json',prior)
log=read('reading-log.json')
log['preliminary_record']='preliminary-turn-1/reading-log.json; exact prior incomplete state retained'
log['status']='COMPLETE_MANDATORY_B09_EXACT_ACT_READING'
log['display_receipts']=[json.loads(x) for x in (D/'display-receipts.jsonl').read_text().splitlines()]
log['qualified_controls'].update(selected_original_IDs=44,additional_residual='GIR-FD82-B033 full original and PLAN objects read separately',limits='43 complete original/acceptance pairs consumed through exact typed values; native ordered map regenerated and pointers/types verified. B033 pair additionally read completely. Unrelated original findings are outside this bounded role.')
log['accepted_owner_control_reading']['limits']='Complete owner ordered structure/leaf map regenerated. Native keys, arrays, type/value selectors and current protected clauses/rows compared; unrelated whole business-domain acceptance is not repeated.'
for t in log['truncations_and_supplements']:
 t['completion_status']='RESOLVED_IN_SCOPE_OR_EXPLICIT_OUT_OF_SCOPE_NAVIGATION'
 t['completion_successor']='reading-completion-successor.json; completion-formal-map.json, completion-audit-map.json, completion-public-map.json and completion-pointer-relationship-checks.json'
for v in ['predecessor_to_ACT','C3_to_ACT']:log['complete_unfiltered_diff_reading'][v]['complete_semantic_read']=True
log['complete_unfiltered_diff_reading']['method']='Both complete unfiltered outer streams captured/inventoried before first judgment. Complete formal body dictionary, current audit corpus exact typed business dictionary and full ten public outer-block/native TSV relationships subsequently consumed. Duplicate values reused only at exact identities and source pointers; metadata/type/order/hash checks are separate from business readings. No raw private-provenance duplication.'
for x in log['changed_new_audit_reading_inventory']:
 if isinstance(x,dict):x['completion_successor']='238 exact fixed ACT files mapped in completion-audit-map.json; all101 business pages read, metadata relationships independently verified; historical programs read as text only'
log['additional_outstanding']=[]
log['completion']=dict(formal_dictionary_units=len(formal['semantic_units']),formal_pages_complete=13,audit_files=238,audit_scalar_occurrences=1232865,audit_original_unique_units=7010,audit_business_units_consumed=len(pages['selected_original_unit_ids']),audit_business_pages_complete=101,public_novel_units_read=148,public_paths=10,metadata_verification='completion-pointer-relationship-checks.json',audit_structure_refinement='completion-audit-structure-successor.json',author_comparison_after_immutable_first_judgment=True,continued_same_review=True)
log['continuation_truncations']=[dict(attempt='Combined business pages95–100 exceeded aggregate output budget; retry also clipped a tool item',supplement='Pages95–97 and98–100 reissued with enlarged bounded tool budgets and fully consumed; original page IDs unchanged'),dict(attempt='Broad own-artifact and registry/schema navigation displays',supplement='Not counted as semantic completion; full unique audit values had already been consumed, current owner clauses/rows and schemas separately delivered, complete native relationships mechanically verified'),dict(attempt='Guessed combined creature catalog filename absent',supplement='No read claimed; named CX40–42 were freshly read in the correct pokemon-rules-wp31-32-37-38.md catalog. Battler near helper filename similarly resolved using exact fixed tree before fresh read.')]
log['remaining_out_of_scope_unread']='All named retained reference/runtime/asset/plugin/host/configuration/serialized/map/event/sample/backup/gen limitations and unrelated whole business-domain acceptance; no mandatory in-scope unread/truncated range remains.'
save('reading-log.json',log)
completion=dict(run_id='20261003-prepare',reviewed_actual=ACT,completed_utc=now,prior_state='REQUEST_CHANGES solely for reviewer reading-completeness gap, not ACT defect',preserved_preliminary_snapshot='preliminary-turn-1/snapshot-receipt.json',first_judgment_sha256=receipt['sha256'],first_judgment_unchanged=True,first_judgment_receipt_unchanged=True,retired_gap=dict(id='R-B09-ACT-READ-001',kind='REVIEW_COMPLETENESS_GAP_NOT_ACT_CONTENT_DEFECT',status='DISCHARGED_BY_SAME_REVIEW_READING_COMPLETION',author_repair=False,new_canonical=False),completed_obligations=log['completion'],native_control_structure_checks=checks['checks'][:9],final_independent_verdict='PASS_SCOPED',scope='SEPARATE_AFFECTED_B09_ACTUAL only',ACT_content_findings=[],mandatory_in_scope_unread=[],remaining_other_gates=['FULL','B02','B03','B04','B06','B07','B08'],acceptance=False,report_commit=None)
save('reading-completion-successor.json',completion)
findings=read('findings.json');findings.update(verdict='PASS_SCOPED',disposition_basis='Completed independent exact-ACT bounded B09 semantic/source/control/integration review; no supported in-scope blocking discrepancy',ACT_content_findings=[],blocking_review_gaps=[],retired_review_gaps=[completion['retired_gap']],empty_content_findings_limit='Empty content findings applies only to the complete named bounded B09 contract and integration relationships. It does not approve other actual gates, unrelated business domains, runtime/media/assets/Demo/backend or B14 acceptance.')
findings['empty_content_findings_inspection_support']+=[ 'All original43 relevant pairs plus complete B033 residual qualification; accepted owner native structures/projections and protected named clauses/rows', 'All735 formal dictionary values through exact current-line reuse or literal complete pages; all101 audit business pages/5748 unique claims, types and source relationships', 'All ten complete public outer diff blocks/native pending TSV relationships; 267 current pointer/order/type/input/registry checks, plus72 planned and140 hash bindings and142 headings', 'Exact three approved patch reconstructions equal ACT; entire protected WP59§3.6/WP39 and unaffected accepted history preserved' ]
findings['reading_completion_successor']='reading-completion-successor.json';save('findings.json',findings)
manifest=read('review-manifest.json');manifest.update(verdict='PASS_SCOPED',quality_gate_complete=True,actual_PASS=True,scope='Complete bounded affected B09 contract and exact ACT integration relationships; no unrelated whole business-domain acceptance or automatic candidate PASS transfer.',completed_utc=now,reading_completion='reading-completion-successor.json',current_B09_gate='PASS_SCOPED at exact reviewed_actual; this report only',remaining_actual_gates=['FULL','B02','B03','B04','B06','B07','B08'],AREG_C='Requires all eight independently supported PASS_SCOPED gates at this same exact ACT; this report does not accept B14')
manifest['configuration']['admission']='Same supported requested CLI profile supplied by coordinator under approved Plan A; effective backend UNVERIFIED, no certificate/probes.'
manifest['report_files']+=['reading-completion-successor.json','completion-formal-map.json','completion-audit-map.json','completion-public-map.json','completion-pointer-relationship-checks.json','completion-audit-structure-successor.json','completion-authorization-reconstruction.json']
save('review-manifest.json',manifest)
inputs=read('input-identities.json');known={(x.get('commit'),x.get('path')) for x in inputs['files']}
for r in log['display_receipts']:
 if r.get('commit') and r.get('path') and (r['commit'],r['path']) not in known:
  inputs['files'].append(identity(r['commit'],r['path'],'FRESH_STATIC_SOURCE' if r.get('repository')=='reference' else 'CURRENT_OR_FIXED_DOCUMENT',r.get('repository')=='reference'));known.add((r['commit'],r['path']))
inputs['identity_roles']['this_report_commit']=None;inputs['identity_roles']['report_policy']='Externally assigned distinct publication commit; exact ACT identifies payload, no recursion.';save('input-identities.json',inputs)
design=read('static-designs.json');design['assessment']='Supported current bounded B09 static positive/reverse designs at exact ACT; unexecuted';assert design['executed']==0;save('static-designs.json',design)
author='''# Author comparison — completed after immutable first judgment

The saved first judgment and receipt remain exact. First-judgment SHA256: `fedc5c70b9dade50d1c774de1106b665624189a0f6591563c1e4fbfb1eef6772`. The preliminary incomplete comparison is preserved in `preliminary-turn-1/author-comparison.md`. Detailed author/C3/G claims were consumed only after that judgment. This successor compares claims with independent ACT evidence; it does not inherit a candidate verdict.

| Claim | Independent exact-ACT result |
| --- | --- |
| Authorized12 formal/49 evidence and eight report directories copied exactly | Verified all216 source copies,10 public successors and34 new G files; both unfiltered streams captured/inventoried without exclusions. No unexpected edit or missing copy. |
| C3 separate tint/new-battle time, correct consumers preserved | Fresh Time/BattleStarting/Battle/Settings/metadata/environment/caller/consumer reads support indoor20 neutral tint/time2, disabled non-Cave default0, Cave-first2 even explicitGrass, and17/12 time1/0 independently of outdoor. Three authorized patches reconstruct ACT; WP59§3.6/WP39§7.3 remain exact. |
| Retained FLY/berry/splash repairs | Independent prefix/exception/cleanup, common timestamp-before-branch and reset255+return checks agree under their legal positive/reverse premises. Later window update must separately be lawful; no source behavior executed. |
| Public24 pending records and correct current locators | Exact170-row prefixes/schema/order preserved;194 total,19primary/5shared appended; complete qualified projections, all8 C3 receipts and current clause/test/source identities agree. Writer actual verdict stays null; prepared null ACT fields are historical payload metadata, externally bound to ACT by this review. |
| 505 retained rows/four additions/current509 | Exact row bytes/terminators/order/multiplicity verified;361engine+148Pokemon. Second catalog C2-identical; unaffected owner segments and original controls/history preserved. Static rows are unexecuted. |
| B09 accepted report corrections and FULL C3 errata | One restoration yields boxedA=Y/liveBempty before outer healing/pickup under actual-partner/full-party/normal-receive premises. Live-user NearAlly far4 selection/registration is rejected only at unchanged normal target resolution; B033 self0 residual remains separate. Calendar matching, enter0→connected20 duration and06:30=138/noon255 qualifications remain report-only. |
| G bookkeeping/read-completeness/configuration claims | New independent lossless dictionary reads and native pointer/type/order checks supply this review's evidence; G hashes/labels alone did not. Effective backend remains UNVERIFIED under Plan A; historical interface/chronology/publication observations remain supplied evidence, not a new backend certificate or remote probe. |

The earlier reading gap R-B09-ACT-READ-001 is discharged by the same review's completed reads and binding checks, without author/formal repair. Final verdict: PASS_SCOPED only for the separate B09 actual gate at d48197f365c39925f795c1d325988c0d74e59979. All other seven actual gates remain independent; B14 remains unaccepted. AREG-C alone may accept after all eight same-ACT gates PASS; B10 then refreezes53 reads/eight writes/contract, with later WP46 reverse obligations retained. Runtime0, provenDemo0 and behavior vectors executed0; all named limits remain.
'''
(D/'author-comparison.md').write_text(author)
rows='\n'.join('| '+r['id']+' | '+r['disposition']+' | '+r['reason']+' |' for r in con['dispositions'])
ownerrows='\n'.join('| '+r['id']+' | '+r['changed_clause_caller_condition_comparison']+' |' for r in owner['dispositions'])
report=f'''# Independent affected B09 exact-ACT review

**PASS_SCOPED** for reviewed ACT `{ACT}`, tree `be4b5ef8960c0e9cfb9eb9ec0e1aded3a35a88df`, sole parent/accepted predecessor `{PRE}`. This verdict covers only the complete bounded affected B09 contract and its integration/public relationships. No supported in-scope ACT content discrepancy remains. B14 is unaccepted; this report supplies one of eight independent actual gates.

Candidate C3 `{C3}`, candidate B09 report `21be87e2a36acd72adb9779388f2d91675bb0a35`, source/reference `{REF}` (tree `7589c800b61ba13a13040ed0d686979b80a84fd0`) and this report's externally assigned commit are separate roles. The report commit is null until mechanical publication. Original qualified controls remain `{ORIG}`; PLAN remains `{PLAN}` in its distinct hyphen directory. Scope proposal/authorization supply permission only.

PASS_SCOPED means completed independent static semantic/source/qualification/preservation/registration assessment at exact ACT within this named role, with no supported blocking mismatch. REQUEST_CHANGES means a supported scoped discrepancy or unmet mandatory review obligation prevents that gate. The preliminary REQUEST_CHANGES was solely a reviewer reading gap, not an ACT defect. Exact snapshots in [preliminary-turn-1](preliminary-turn-1/snapshot-receipt.json) preserve it. The [first judgment](independent-first-judgment.md) and immutable receipt remain unchanged. [Reading completion](reading-completion-successor.json) discharges R-B09-ACT-READ-001 after completing the required reads; no formal repair or candidate PASS transfer occurred.

| Complete unfiltered stream | Paths | Bytes | SHA256 |
| --- | --- | --- | --- |
| Accepted predecessor→ACT |260|96116311|1f88e677993c91905b72b747b187f6e94a52881178b08716fe6791bd6cbab444|
| C3→ACT |199|95127902|5d639c30c53bb37035d2d133b715da5cc5c706afd13d278c8a7ad718368da5d9|

Both streams use `--no-ext-diff --no-textconv --no-renames --binary --full-index --no-color`, with no path exclusion. Complete path/hunk/identity inventories preceded judgment; subsequent exact typed dictionaries consumed every distinct business value with fixed source/context mappings and native order. All13 formal pages/735 values (including exact same-review current-line reuse), all101 audit business pages/5748 unique claims across238 audit files, and all148 novel public values/native TSV relationships are complete. Identity, type/order/pointer and hash work is separately recorded, never behavior evidence. Every in-scope truncation was supplemented. Raw diff duplication is omitted because of historical private provenance; full endpoints/hash/bytes/flags and complete maps remain reproducible. See [reading log](reading-log.json), [diff inventories](diff-inventories.json), [pointer checks](completion-pointer-relationship-checks.json) and [authorization reconstruction](completion-authorization-reconstruction.json).

All12 formal and49 evidence paths are exact C3 copies;155 candidate-report files are exact copies at their eight distinct supplied report commits. Ten bounded public paths and34 new G files account for all260 changes; no unexpected path, missing copy or unpermitted semantic edit was found. Other accepted B01–B09 formal/public/approval/history bytes remain protected outside the explicit changes. All72 planned identities and140 current hashes agree; two historical original-review inputs retain fixed external binding. Old B09-G freeze/reports remain immutable. All142 current heading bindings include exact line terminators and correct named sections; WP16's scope is the single5.1.1 splash sentence.

Both public registries preserve exact schemas/column order and all170 accepted row bytes. Exactly24 B14 records append,19primary/five shared,194 total=170accepted+24pending. All canonical IDs remain OPEN; distinct B14 contribution keys avoid shared-ID double counting. Qualified controls, source/current clause/test identities, C3 and all8 candidate receipts and pending actual obligations agree. Neither a report SHA nor a candidate SHA is substituted for ACT. Prepared null/future ACT labels are immutable G payload metadata; this review binds external ACT and does not rewrite them. No early acceptance, canonical root/extension addition or closure occurs.

Fresh full WP39/WP40, required WP38/WP42/WP41/WP20 clauses, current WP59/fishing/berry/WP61 bodies and named owner catalog rows were inspected. Complete original/PLAN qualified objects for43 distinct contribution IDs plus the separate B033 residual were consumed, with all current qualifications/effective cases/root/extension decisions governing over raw history. Accepted B09 controls and their complete native mappings remain exact. Architecture-neutral capability/stage/plot/participant terms preserve compatibility identities, partial-write order and genuine entry differences without prescribing source hierarchy or containers.

Independent tint and ordinary new-battle preparation have separate observation points. With legal new battle, able player, valid nonempty opponents/dependencies, stable local sample and no skip/interception/plugin/alias/external rewrite/explicit time mutation: non-Cave indoor/shadingtrue/hour20 gives neutral map tint and battle time2; outdoor toggles tint eligibility only. Non-Cave shadingfalse retains new default0. Map metadata Cave forces2 before shading even with valid explicitGrass battle environment. Non-Cave shadingtrue17/12 gives1/0 for either outdoor value. WT41–44 remain unexecuted. WP59§3.6 and WP39§7.3 are preserved; no pixel/background-asset/capture-probability claim follows.

Preserved observations retain their original IDs and premises: FLY optional throwing callback commits count/transfer/music/refresh, propagates after normal fade cleanup, skips wait/record clears/normaltrue and retains E/D; absent/normal callback reaches the normal tail. A later window update must independently be lawful. Berry common lifetime→stage→timestamp precedes watering/drying, excluding unplanted/nonpositive/replant-return paths. Splash reset writes opacity255 and immediately returns, distinct from ordinary nonreset remaining<0.2. Actual-partner/full-party receive retains shared old participants and a single restoration, boxedA=Y/liveBempty before outer healing/pickup. NearAlly liveuser0/faintednear2/noreserve/livefar4 selects and registers4, then unchanged normal resolution rejects it without an effect/PP/message judgment. No-live-nonself self0 remains separate B033.

All505 C2 rows retain exact bytes/terminators/order/multiplicity; four additions give509 (engine361/Pokemon148). Whole second catalog is C2-identical. Unaffected owner segments/common premises remain exact from the accepted predecessor. Fishing15-versus16 successor navigation preserves old report bytes; FS16 restores the separate valid-start design and FS17–18 add contrasts. FULL C3 R-B14-C3-EVID-001/002/003 remain HISTORICAL_REPORT_ONLY_QUALIFICATION: calendar candidate matching, enter duration0 then connected20,06:30brightness138/noon255. Correct formal behavior is not altered to repair historical report prose. Daily infected non-egg decrement remains distinct from capture-before-fixed-source neighbor propagation.

| Current B14 contribution | B09-role disposition | Changed clause/caller/condition and preserved contract reasoning |
| --- | --- | --- |
{rows}

These dispositions evaluate B09 interfaces and registration only. Supported NOT_AFFECTED names a current changed clause/caller/condition and preserved B09 input; it never grants unrelated full contribution approval. Complete qualified per-ID objects, locators and candidate receipts remain in [contribution dispositions](contribution-dispositions.json).

| Accepted B09 contribution | Current protected owner comparison |
| --- | --- |
{ownerrows}

Each accepted control stays at the fixed predecessor; current owner inputs bind ACT. See [owner dispositions](owner-dispositions.json) and [prior observations](prior-observation-dispositions.json). Historical acceptance and candidate receipts are not automatically transferred. [Author comparison](author-comparison.md) occurred only after the immutable first judgment.

Requested/supplied same supported CLI profile: gpt-6.1-sol/ultra/service_tier default (documented Standard). Effective backend **UNVERIFIED under approved Plan A**; no invented certificate, settings/auth/quota probe or substitution. One reviewer, no children/nested agents/other sessions/messages/processworkers or dispatch. Writes stay inside this unpublished report directory. No Git stage/commit/push/fetch/switch/index/ref write, reference mutation/execution or historical author/reviewer/verifier execution was performed. Only new document/hash/JSON/diff bookkeeping ran.

All seven classifications, U01–U10/G01–G12/AX01–AX20 and named binary/serialized/map/event/media/resource/host/plugin/configuration/sample/backup/gen/unlisted-source limits remain; no unconditional67-berry obligation, real screen/audio/assets/capacity/backend validation. Runtime observations0, provenDemo0, behavior vectors executed0. Statistics remain9/21 accepted,170records,142touched,109primary, minimum109satisfied, strict100satisfied+9pending,229OPEN/0CLOSED; B14unaccepted24/19.

Exact actual-only handoff: mechanically publish this completed B09 report and assign its distinct report commit. FULL/B02/B03/B04/B06/B07/B08 remain separate mandatory same-ACT gates; their status is not decided here. AREG-C alone can accept after all eight actual gates PASS at this exact ACT. B10 then refreezes53reads/eightwrites/contract before formal work; later WP46 reverse obligations remain. No task dispatch or acceptance is supplied.
'''
(D/'report.md').write_text(report)
print('Completed B09 exact-ACT report artifacts; first judgment unchanged; PASS_SCOPED scope only, no B14 acceptance.')
